import './globals.css'

import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

import Nav from './components/Nav'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Check if user is authenticated
  const session = await getServerSession(authOptions)

  const user = {
    ...session?.user,
    expires: session?.expires,
  }

  console.log(session)

  return (
    <html lang="en">
      <body className='mx-64' >
        <Nav user={user} expires={session?.expires as string} />
      </body>
    </html>
  )
}
